import json
import uuid
import shutil

checkpoint_path = r"c:\Users\Dhaval\OneDrive\Desktop\SEM 5\ML\ML_PROJECT\.ipynb_checkpoints\movie-recommender-system-checkpoint.ipynb"
notebook_path = r"c:\Users\Dhaval\OneDrive\Desktop\SEM 5\ML\ML_PROJECT\movie-recommender-system.ipynb"

# 1. Restore the original notebook from checkpoint
print("Restoring original notebook from checkpoint...")
shutil.copy2(checkpoint_path, notebook_path)

# 2. Load the restored notebook
with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Truncate any cells after the original ones (if any exist)
last_original_idx = -1
for idx, cell in enumerate(nb["cells"]):
    source = "".join(cell.get("source", []))
    if "movies['crew'][0]" in source:
        last_original_idx = idx
        break

if last_original_idx != -1:
    print(f"Found original ending cell at index {last_original_idx}. Appending new cells after it.")
    nb["cells"] = nb["cells"][:last_original_idx + 1]
else:
    # If not found, let's find the last non-empty original cell or just append to the end of the 46 cells.
    # The original checkpoint has 46 cells (indices 0 to 45).
    # Let's ensure we keep only the first 46 cells of the checkpoint.
    nb["cells"] = nb["cells"][:46]
    print(f"Restoring to original {len(nb['cells'])} cells from checkpoint.")

# Define new cells to append
new_cells = [
    {
        "cell_type": "markdown",
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "source": [
            "## Week 2: Data Cleaning and Pre-processing (Remaining Tasks)\n",
            "\n",
            "In this section, we complete the following Week 2 tasks:\n",
            "1. **Outliers Detection & Handling** (using IQR capping/Winsorization)\n",
            "2. **Categorical Encoding** (using LabelEncoder)\n",
            "3. **Feature Scaling / Normalization** (using MinMaxScaler)\n",
            "4. **Exploratory Data Analysis (EDA)** (correlation heatmap, budget vs revenue scatter plot, and movie popularity analysis)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "outputs": [],
        "source": [
            "# Outliers Detection and Capping (Winsorization)\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "# Define numeric columns\n",
            "num_cols = ['budget', 'popularity', 'revenue', 'runtime', 'vote_average', 'vote_count']\n",
            "\n",
            "# Visualize boxplots before outlier handling\n",
            "plt.figure(figsize=(15, 8))\n",
            "for i, col in enumerate(num_cols, 1):\n",
            "    plt.subplot(2, 3, i)\n",
            "    plt.boxplot(movies[col].dropna())\n",
            "    plt.title(f'Boxplot of {col} (Before)')\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# Function to cap outliers using IQR method\n",
            "def handle_outliers_iqr(df, columns):\n",
            "    df_cleaned = df.copy()\n",
            "    for col in columns:\n",
            "        Q1 = df_cleaned[col].quantile(0.25)\n",
            "        Q3 = df_cleaned[col].quantile(0.75)\n",
            "        IQR = Q3 - Q1\n",
            "        lower_bound = Q1 - 1.5 * IQR\n",
            "        upper_bound = Q3 + 1.5 * IQR\n",
            "        # Cap values\n",
            "        df_cleaned[col] = np.clip(df_cleaned[col], lower_bound, upper_bound)\n",
            "    return df_cleaned\n",
            "\n",
            "# Apply outlier capping\n",
            "movies = handle_outliers_iqr(movies, num_cols)\n",
            "\n",
            "# Visualize boxplots after outlier handling\n",
            "plt.figure(figsize=(15, 8))\n",
            "for i, col in enumerate(num_cols, 1):\n",
            "    plt.subplot(2, 3, i)\n",
            "    plt.boxplot(movies[col])\n",
            "    plt.title(f'Boxplot of {col} (After Capping)')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "outputs": [],
        "source": [
            "# Encode Categorical Variables\n",
            "from sklearn.preprocessing import LabelEncoder\n",
            "\n",
            "cat_cols = ['original_language', 'status']\n",
            "label_encoders = {}\n",
            "\n",
            "for col in cat_cols:\n",
            "    le = LabelEncoder()\n",
            "    # Fill any NaNs with string representation\n",
            "    movies[col] = movies[col].fillna('unknown').astype(str)\n",
            "    movies[col] = le.fit_transform(movies[col])\n",
            "    label_encoders[col] = le\n",
            "\n",
            "print(\"Encoded categorical variables (original_language, status):\")\n",
            "print(movies[cat_cols].head())"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "outputs": [],
        "source": [
            "# Normalize / Scale Numerical Features\n",
            "from sklearn.preprocessing import MinMaxScaler\n",
            "\n",
            "scaler = MinMaxScaler()\n",
            "# Fill remaining numerical NaNs with column median before scaling\n",
            "for col in num_cols:\n",
            "    movies[col] = movies[col].fillna(movies[col].median())\n",
            "\n",
            "movies[num_cols] = scaler.fit_transform(movies[num_cols])\n",
            "\n",
            "print(\"Scaled numerical features (budget, popularity, revenue, runtime, vote_average, vote_count):\")\n",
            "print(movies[num_cols].head())"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "outputs": [],
        "source": [
            "# Exploratory Data Analysis (EDA)\n",
            "import seaborn as sns\n",
            "\n",
            "# 1. Correlation Heatmap\n",
            "plt.figure(figsize=(10, 8))\n",
            "sns.heatmap(movies[num_cols].corr(), annot=True, cmap='coolwarm', fmt=\".2f\")\n",
            "plt.title(\"Correlation Matrix of Numeric Features\")\n",
            "plt.show()\n",
            "\n",
            "# 2. Scatter plot: Budget vs Revenue\n",
            "plt.figure(figsize=(8, 6))\n",
            "plt.scatter(movies['budget'], movies['revenue'], alpha=0.5, color='purple')\n",
            "plt.title(\"Budget vs Revenue (Scaled)\")\n",
            "plt.xlabel(\"Scaled Budget\")\n",
            "plt.ylabel(\"Scaled Revenue\")\n",
            "plt.show()\n",
            "\n",
            "# 3. Bar plot of Top 10 Movies by Popularity\n",
            "top_10_pop = movies.nlargest(10, 'popularity')\n",
            "plt.figure(figsize=(10, 6))\n",
            "sns.barplot(x=top_10_pop['popularity'], y=top_10_pop['title'], palette='magma')\n",
            "plt.title(\"Top 10 Most Popular Movies (Scaled)\")\n",
            "plt.xlabel(\"Scaled Popularity\")\n",
            "plt.ylabel(\"Movie Title\")\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "source": [
            "## Week 3: Model Creation\n",
            "\n",
            "In this section, we implement a content-based movie recommender system using two approaches:\n",
            "1. **Library-based Recommender**: Using `scikit-learn`'s `CountVectorizer` and `cosine_similarity`.\n",
            "2. **From-Scratch Recommender**: Implementing both vectorization and similarity calculations manually in pure Python (meeting the scratch implementation constraint)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "outputs": [],
        "source": [
            "# Text Preprocessing for Content-based Recommendation\n",
            "import ast\n",
            "\n",
            "# Robust converter functions to extract names from JSON or pre-parsed columns\n",
            "def convert_genres_keywords(obj):\n",
            "    if isinstance(obj, list):\n",
            "        L = []\n",
            "        for i in obj:\n",
            "            if isinstance(i, dict) and 'name' in i:\n",
            "                L.append(i['name'])\n",
            "            elif isinstance(i, str):\n",
            "                L.append(i)\n",
            "        return L\n",
            "    try:\n",
            "        L = []\n",
            "        for i in ast.literal_eval(obj):\n",
            "            L.append(i['name'])\n",
            "        return L\n",
            "    except Exception:\n",
            "        return []\n",
            "\n",
            "def convert_cast(obj):\n",
            "    if isinstance(obj, list):\n",
            "        L = []\n",
            "        for i in obj:\n",
            "            if isinstance(i, dict) and 'name' in i:\n",
            "                L.append(i['name'])\n",
            "            elif isinstance(i, str):\n",
            "                L.append(i)\n",
            "        return L[:3]\n",
            "    try:\n",
            "        L = []\n",
            "        counter = 0\n",
            "        for i in ast.literal_eval(obj):\n",
            "            if counter != 3:\n",
            "                L.append(i['name'])\n",
            "                counter += 1\n",
            "            else:\n",
            "                break\n",
            "        return L\n",
            "    except Exception:\n",
            "        return []\n",
            "\n",
            "def fetch_director(obj):\n",
            "    if isinstance(obj, list):\n",
            "        L = []\n",
            "        for i in obj:\n",
            "            if isinstance(i, dict) and i.get('job') == 'Director' and 'name' in i:\n",
            "                L.append(i['name'])\n",
            "                break\n",
            "            elif isinstance(i, str):\n",
            "                L.append(i)\n",
            "        return L[:1]\n",
            "    try:\n",
            "        L = []\n",
            "        for i in ast.literal_eval(obj):\n",
            "            if i['job'] == 'Director':\n",
            "                L.append(i['name'])\n",
            "                break\n",
            "        return L\n",
            "    except Exception:\n",
            "        return []\n",
            "\n",
            "# Apply converters\n",
            "movies['genres'] = movies['genres'].apply(convert_genres_keywords)\n",
            "movies['keywords'] = movies['keywords'].apply(convert_genres_keywords)\n",
            "movies['cast'] = movies['cast'].apply(convert_cast)\n",
            "movies['crew'] = movies['crew'].apply(fetch_director)\n",
            "\n",
            "# Strip spaces from words to make them single tags (e.g. \"Johnny Depp\" -> \"johnnydepp\")\n",
            "movies['genres'] = movies['genres'].apply(lambda x: [i.replace(\" \", \"\") for i in x])\n",
            "movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(\" \", \"\") for i in x])\n",
            "movies['cast'] = movies['cast'].apply(lambda x: [i.replace(\" \", \"\") for i in x])\n",
            "movies['crew'] = movies['crew'].apply(lambda x: [i.replace(\" \", \"\") for i in x])\n",
            "\n",
            "# Convert overview column to a list of tokens\n",
            "movies['overview'] = movies['overview'].apply(lambda x: x.split() if isinstance(x, str) else [])\n",
            "\n",
            "# Combine all text columns into a single 'tags' column\n",
            "movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']\n",
            "\n",
            "# Create a new clean dataframe\n",
            "new_df = movies[['id', 'title', 'tags']].copy()\n",
            "new_df['tags'] = new_df['tags'].apply(lambda x: \" \".join(x))\n",
            "new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())\n",
            "\n",
            "# Apply stemming to group similar words (with safe NLTK import fallback)\n",
            "try:\n",
            "    import nltk\n",
            "    from nltk.stem.porter import PorterStemmer\n",
            "    ps = PorterStemmer()\n",
            "    def stem(text):\n",
            "        y = []\n",
            "        for i in text.split():\n",
            "            y.append(ps.stem(i))\n",
            "        return \" \".join(y)\n",
            "except ImportError:\n",
            "    print(\"NLTK not found. Proceeding with standard lowercased tags.\")\n",
            "    def stem(text):\n",
            "        return text\n",
            "\n",
            "new_df['tags'] = new_df['tags'].apply(stem)\n",
            "print(\"Finished preprocessing tags. Head of new DataFrame:\")\n",
            "print(new_df[['title', 'tags']].head())"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "outputs": [],
        "source": [
            "# Library-based Recommender (sklearn CountVectorizer & cosine_similarity)\n",
            "from sklearn.feature_extraction.text import CountVectorizer\n",
            "from sklearn.metrics.pairwise import cosine_similarity\n",
            "\n",
            "cv = CountVectorizer(max_features=5000, stop_words='english')\n",
            "vectors = cv.fit_transform(new_df['tags']).toarray()\n",
            "similarity = cosine_similarity(vectors)\n",
            "\n",
            "def recommend(movie):\n",
            "    try:\n",
            "        movie_index = new_df[new_df['title'].str.lower() == movie.lower()].index[0]\n",
            "        distances = similarity[movie_index]\n",
            "        movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]\n",
            "        \n",
            "        print(f\"Recommendations for '{movie}' (Library-based):\")\n",
            "        for i in movies_list:\n",
            "            print(f\"- {new_df.iloc[i[0]]['title']}\")\n",
            "    except IndexError:\n",
            "        print(f\"Movie '{movie}' not found in the dataset.\")\n",
            "\n",
            "# Test library recommender\n",
            "recommend('Avatar')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": str(uuid.uuid4())[:8],
        "metadata": {},
        "outputs": [],
        "source": [
            "# From-Scratch Recommender (Custom vectorization & Cosine Similarity in Pure Python)\n",
            "import collections\n",
            "import math\n",
            "\n",
            "class CustomCountVectorizer:\n",
            "    def __init__(self, max_features=5000, stop_words='english'):\n",
            "        self.max_features = max_features\n",
            "        self.stop_words = stop_words\n",
            "        self.vocabulary_ = {}\n",
            "        \n",
            "    def fit_transform(self, raw_documents):\n",
            "        # Count document term frequency\n",
            "        word_counts = collections.Counter()\n",
            "        \n",
            "        # Simple list of English stopwords\n",
            "        stopwords = {\n",
            "            'a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', 'as', 'at', \n",
            "            'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'cannot', 'could', \n",
            "            'did', 'do', 'does', 'doing', 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'has', 'have', \n",
            "            'having', 'he', 'her', 'here', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'i', 'if', 'in', 'into', 'is', \n",
            "            'it', 'its', 'itself', 'me', 'more', 'most', 'my', 'myself', 'no', 'nor', 'not', 'of', 'off', 'on', 'once', \n",
            "            'only', 'or', 'other', 'ought', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'same', 'she', 'should', \n",
            "            'so', 'some', 'such', 'than', 'that', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', \n",
            "            'these', 'they', 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 'very', 'was', 'we', 'were', \n",
            "            'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'with', 'would', 'you', 'your', 'yours', \n",
            "            'yourself', 'yourselves'\n",
            "        }\n",
            "        \n",
            "        for doc in raw_documents:\n",
            "            tokens = doc.lower().split()\n",
            "            filtered_tokens = [t for t in tokens if t.isalnum() and (self.stop_words != 'english' or t not in stopwords)]\n",
            "            word_counts.update(filtered_tokens)\n",
            "            \n",
            "        # Filter by top max_features\n",
            "        top_words = [word for word, count in word_counts.most_common(self.max_features)]\n",
            "        self.vocabulary_ = {word: idx for idx, word in enumerate(top_words)}\n",
            "        \n",
            "        # Build word vectors\n",
            "        vectors = []\n",
            "        for doc in raw_documents:\n",
            "            tokens = doc.lower().split()\n",
            "            doc_vec = [0] * len(self.vocabulary_)\n",
            "            for t in tokens:\n",
            "                if t in self.vocabulary_:\n",
            "                    doc_vec[self.vocabulary_[t]] += 1\n",
            "            vectors.append(doc_vec)\n",
            "            \n",
            "        return np.array(vectors)\n",
            "\n",
            "# Run custom vectorizer\n",
            "ccv = CustomCountVectorizer(max_features=5000)\n",
            "custom_vectors = ccv.fit_transform(new_df['tags'])\n",
            "\n",
            "# Custom cosine similarity calculation\n",
            "def cosine_similarity_scratch(vec_a, vec_b):\n",
            "    dot_product = sum(a * b for a, b in zip(vec_a, vec_b))\n",
            "    norm_a = math.sqrt(sum(a * a for a in vec_a))\n",
            "    norm_b = math.sqrt(sum(b * b for b in vec_b))\n",
            "    if norm_a == 0 or norm_b == 0:\n",
            "        return 0.0\n",
            "    return dot_product / (norm_a * norm_b)\n",
            "\n",
            "def recommend_scratch(movie):\n",
            "    try:\n",
            "        # Find movie index\n",
            "        movie_indices = new_df[new_df['title'].str.lower() == movie.lower()].index\n",
            "        if len(movie_indices) == 0:\n",
            "            raise IndexError\n",
            "        movie_index = movie_indices[0]\n",
            "        query_vector = custom_vectors[movie_index]\n",
            "\n",
            "        # Compute similarity dynamically against all other movies\n",
            "        scores = []\n",
            "        for idx, vec in enumerate(custom_vectors):\n",
            "            score = cosine_similarity_scratch(query_vector, vec)\n",
            "            scores.append((idx, score))\n",
            "\n",
            "        # Sort recommendations excluding the query movie itself\n",
            "        scores = sorted(scores, key=lambda x: x[1], reverse=True)\n",
            "        recommended = [s for s in scores if s[0] != movie_index][:5]\n",
            "\n",
            "        print(f\"Recommendations for '{movie}' (From-Scratch):\")\n",
            "        for i in recommended:\n",
            "            print(f\"- {new_df.iloc[i[0]]['title']}\")\n",
            "    except IndexError:\n",
            "        print(f\"Movie '{movie}' not found in the dataset.\")\n",
            "\n",
            "# Test custom recommender\n",
            "recommend_scratch('Avatar')"
        ]
    }
]

# Append the new cells
nb["cells"].extend(new_cells)

# Save the updated notebook
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Notebook restored from checkpoint and updated successfully!")
